spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpatest?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    #      create = drop -> create
    #     create-drop = drop -> create -> drop
    #     update = create -> alter (???? ??? ???? ???)
    #     none = x
    show-sql: true